kind: Deployment
apiVersion: apps/v1  
metadata:
  name:  webapp 
  namespace: dev    
  labels:
    app: be  
spec: 
  replicas: 1     
  selector:
    matchLabels:
      app: web  
  template:
    metadata:
      name: webapp 
      labels: 
        app: web  
    spec: 
      containers:
      - name: webappc
        image: mylandmarktech/maven-web-app  
        ports:
        - containerPort: 8080  

webappsvc.yml  
-------------
kind: Service  
apiVersion: v1  
metadata:
  name: webappsvc  
spec:
  selector:
    app: web  
  type: NodePort 
  ports:
  - port: 80 
    targetPort: 8080
    nodePort: 31000 #[30000-32676]
