apiVersion: v1
kind: Pod
metadata: 
  name: javawebapp   
spec:
  containers:
  - name: javawebapp 
    image: mylandmarktech/java-web-app   
    ports:
    - containerPort: 8080   
    resources:
      requests:
        memory: "128Mi"
        cpu: "500m"          
      limits:
        memory: "512Mi"
        cpu: "1000m"
