---
- name: Install Apache2 on Ubuntu
  hosts: all
  become: yes  
  tasks:
  - name: Test connection
    ping:
  tasks:
    - name: OS update
      apt:
        update_cache: yes
  
    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Start Apache2 service
      service:
        name: apache2
        state: started
        enabled: yes
          
    - name: Create index.html file
      copy:
        content: "<html><head><title>kingsofdevops.com</title></head><body><h1>Hello, Africa! We are the FUTURE BILLIONAIRES. STAY TUNED!!</h1></body></html>"
        dest: /var/www/html/index.html
